# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='manager.proto',
  package='managerpc',
  syntax='proto3',
  serialized_options=b'\242\002\003MNG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmanager.proto\x12\tmanagerpc\"\x18\n\x16RunningServicesRequest\"F\n\x17RunningServicesResponse\x12+\n\x08services\x18\x01 \x03(\x0b\x32\x19.managerpc.RunningService\"\x1e\n\x0eRunningService\x12\x0c\n\x04name\x18\x01 \x01(\t2f\n\x08Mangager\x12Z\n\x0fRunningServices\x12!.managerpc.RunningServicesRequest\x1a\".managerpc.RunningServicesResponse\"\x00\x42\x06\xa2\x02\x03MNGb\x06proto3'
)




_RUNNINGSERVICESREQUEST = _descriptor.Descriptor(
  name='RunningServicesRequest',
  full_name='managerpc.RunningServicesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=52,
)


_RUNNINGSERVICESRESPONSE = _descriptor.Descriptor(
  name='RunningServicesResponse',
  full_name='managerpc.RunningServicesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='services', full_name='managerpc.RunningServicesResponse.services', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=124,
)


_RUNNINGSERVICE = _descriptor.Descriptor(
  name='RunningService',
  full_name='managerpc.RunningService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='managerpc.RunningService.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=156,
)

_RUNNINGSERVICESRESPONSE.fields_by_name['services'].message_type = _RUNNINGSERVICE
DESCRIPTOR.message_types_by_name['RunningServicesRequest'] = _RUNNINGSERVICESREQUEST
DESCRIPTOR.message_types_by_name['RunningServicesResponse'] = _RUNNINGSERVICESRESPONSE
DESCRIPTOR.message_types_by_name['RunningService'] = _RUNNINGSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RunningServicesRequest = _reflection.GeneratedProtocolMessageType('RunningServicesRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGSERVICESREQUEST,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:managerpc.RunningServicesRequest)
  })
_sym_db.RegisterMessage(RunningServicesRequest)

RunningServicesResponse = _reflection.GeneratedProtocolMessageType('RunningServicesResponse', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGSERVICESRESPONSE,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:managerpc.RunningServicesResponse)
  })
_sym_db.RegisterMessage(RunningServicesResponse)

RunningService = _reflection.GeneratedProtocolMessageType('RunningService', (_message.Message,), {
  'DESCRIPTOR' : _RUNNINGSERVICE,
  '__module__' : 'manager_pb2'
  # @@protoc_insertion_point(class_scope:managerpc.RunningService)
  })
_sym_db.RegisterMessage(RunningService)


DESCRIPTOR._options = None

_MANGAGER = _descriptor.ServiceDescriptor(
  name='Mangager',
  full_name='managerpc.Mangager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=260,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunningServices',
    full_name='managerpc.Mangager.RunningServices',
    index=0,
    containing_service=None,
    input_type=_RUNNINGSERVICESREQUEST,
    output_type=_RUNNINGSERVICESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANGAGER)

DESCRIPTOR.services_by_name['Mangager'] = _MANGAGER

# @@protoc_insertion_point(module_scope)
