name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    steps:
      - 
        name: Run graphql query to get tag
        uses: octokit/graphql-action@v2.x
        id: latest_tag
        with:
          query: |
            query tag($owner: String!, $repo: String!) {
              repository(owner: $owner, name: $repo) {
                refs(refPrefix: "refs/tags/", last: 1, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {
                  edges {
                    node {
                      name
               } } } } }
          repo: lndmanage
          owner: bitromortac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Parse tag from query output
        run: |
          #!/bin/bash
          latest_tag=$(echo '${{ steps.latest_tag.outputs.data }}' | jq '.repository.refs.edges[][].name' -r)
          [ -z "$latest_tag" ] && echo "Tag not found!" && exit 1
          [[ "$latest_tag" = v* ]] && latest_tag="${latest_tag:1}"
          echo "Found tag: \"${latest_tag}\"" 
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - 
        name: Check if the tag exists in DockerHub
        id: check-tag
        run: |
          #!/bin/bash
          dockerhub_tags=$(curl -s https://hub.docker.com/v2/repositories/${{ github.repository }}/tags | jq -r '.results[].name')
          if echo "${dockerhub_tags}" | grep -qx "${{ env.latest_tag }}"; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi
      - 
        name: Checkout
        if: env.exists == 'false'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0          
      - 
        name: Set up Docker Buildx
        if: env.exists == 'false'
        uses: docker/setup-buildx-action@v3
      -
        name: Prepare Docker build
        if: env.exists == 'false'
        id: prepare
        run: |
        
          PLATFORMS="linux/amd64,linux/arm64"
          
          TAGS=()
          TAGS=("${{ github.repository }}:latest")
          TAGS+=("${{ github.repository }}:${{ env.latest_tag }}")
          TAGS+=("ghcr.io/${{ github.repository }}:latest")
          TAGS+=("ghcr.io/${{ github.repository }}:${{ env.latest_tag }}")
          
          echo "tags=${TAGS[@]}" >> $GITHUB_OUTPUT
          echo "version=${{ env.latest_tag }}" >> $GITHUB_OUTPUT
          echo "docker_platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT      
      - 
        name: Clone branch
        if: env.exists == 'false'
        run: |
          rm -r lndmanage
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone --recurse-submodules -j8 https://github.com/bitromortac/lndmanage.git --single-branch --branch master
          #git clone --recurse-submodules -j8 https://github.com/bitromortac/lndmanage.git --single-branch --branch v${{ steps.prepare.outputs.version }}
          cp docker/Dockerfile lndmanage/docker/
          cp .dockerignore lndmanage/
      -
        name: Login into Docker Hub
        if: env.exists == 'false'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        if: env.exists == 'false'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build Docker image
        if: env.exists == 'false'
        run: |
        
          TAGS=(${{ steps.prepare.outputs.tags }})

          echo "Build date: ${{ steps.prepare.outputs.build_date }}"
          echo "Docker platform: ${{ steps.prepare.outputs.docker_platforms }}"
          echo "Tags: ${{ steps.prepare.outputs.tags }}"

          cd lndmanage
          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --progress=plain \
            --file ./docker/Dockerfile \
            --build-arg "BUILD_ARG=${GITHUB_RUN_ID}" \
            --build-arg "VERSION_ARG=${{ steps.prepare.outputs.version }}" \
            --build-arg "DATE_ARG=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) .
      -
        name: Clear Docker credentials
        if: env.exists == 'false'
        run: |
          rm -f ${HOME}/.docker/config.json
      -
        name: Create a release
        if: env.exists == 'false'
        uses: action-pack/github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ steps.prepare.outputs.version }}"
          title: "v${{ steps.prepare.outputs.version }}"
      -
       name: Send mail
       if: env.exists == 'false'
       uses: dawidd6/action-send-mail@v3
       with:
         to: ${{secrets.MAILTO}}
         from: Github Actions <${{secrets.MAILTO}}>
         connection_url: ${{secrets.MAIL_CONNECTION}}
         subject: Build of ${{ github.event.repository.name }} v${{ steps.prepare.outputs.version }} completed
         body: |
              The build job of ${{ github.event.repository.name }} v${{ steps.prepare.outputs.version }} was completed successfully! 
              
              See https://github.com/${{ github.repository }}/actions for more information.
