name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'
      - 'LICENSE'
      - 'MANIFEST.in'
      - 'logo.png'
      - 'requirements.txt'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps: 
    - uses: actions/checkout@v3
    -
      name: Build the Docker image
      run: |
              docker build . \
              --file ./docker/Dockerfile \
              --label "build=${GITHUB_RUN_ID}" \
              --label "version=${{ vars.MAJOR }}.${{ vars.MINOR }}" \
              --tag "${{ github.repository }}:latest" \
              --tag "${{ github.repository }}:${{ vars.MAJOR }}.${{ vars.MINOR }}"
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ vars.DOCKERHUB_TOKEN }}
    -
      name: Push to DockerHub
      run: |
              docker push "${{ github.repository }}:${{ vars.MAJOR }}.${{ vars.MINOR }}" &&\
              docker push "${{ github.repository }}:latest"

release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    -
      name: Create a release
      uses: kroese/github-release@v5
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      with:
        tag: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
        title: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
        body: "Release v${{ vars.MAJOR }}.${{ vars.MINOR }}"
    -
      name: Increment minor version
      run: |
        echo "NEW_MINOR=$((${{ vars.MINOR }}+1))" >> $GITHUB_ENV
    -
      name: Update minor version variable
      uses: kroese/set-variable@v4
      with:
        name: 'MINOR'
        value: ${{ env.NEW_MINOR }}
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
