name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'
      - 'LICENSE'
      - 'MANIFEST.in'
      - 'logo.png'
      - 'requirements.txt'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read    
    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Prepare Docker build
        id: prepare
        run: |
        
          PLATFORMS="linux/amd64,linux/arm64"
          VERSION="${{ vars.MAJOR }}.${{ vars.MINOR }}"
          
          TAGS=()
          TAGS=("${{ github.repository }}:latest")
          TAGS+=("${{ github.repository }}:${VERSION}")
          TAGS+=("ghcr.io/${{ github.repository }}:latest")
          TAGS+=("ghcr.io/${{ github.repository }}:${VERSION}")
          
          echo "tags=${TAGS[@]}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "docker_platforms=${PLATFORMS}" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      -
        name: Login into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build Docker image
        run: |
        
          TAGS=(${{ steps.prepare.outputs.tags }})

          echo "Build date: ${{ steps.prepare.outputs.build_date }}"
          echo "Docker platform: ${{ steps.prepare.outputs.docker_platforms }}"
          echo "Tags: ${{ steps.prepare.outputs.tags }}"

          docker buildx build --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --progress=plain \
            --build-arg "BUILD_ARG=${GITHUB_RUN_ID}" \
            --build-arg "VERSION_ARG=${{ steps.prepare.outputs.version }}" \
            --build-arg "DATE_ARG=${{ steps.prepare.outputs.build_date }}" \
            --build-arg "VCS_REF=${GITHUB_SHA::8}" \
            $(printf "%s" "${TAGS[@]/#/ --tag }" ) .
      -
        name: Clear Docker credentials
        run: |
          rm -f ${HOME}/.docker/config.json
      -
        name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_ENV
      -
        name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          writeToFile: false
          reverseOrder: true
          includeInvalidCommits: true
          excludeTypes: "docs,build,chore"
      -
        name: Create a release
        uses: action-pack/github-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ steps.prepare.outputs.version }}"
          title: "v${{ steps.prepare.outputs.version }}"
          body: |
            ${{ steps.changelog.outputs.changes }}

            **Full Changelog**: https://github.com/${{ github.repository }}/compare//${{ env.previousTag }}...v${{ steps.prepare.outputs.version }}
      -
        name: Increment version variable
        uses: action-pack/bump@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
