name: Update
on:
  push:
    branches:
      - master
    paths:
      - .github/readme.md
      - .github/workflows/hub.yml

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - 
      name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ github.repository }}
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./.github/readme.md
